<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Digisol" ignored="0" name="Test(failed)" tests="2" failures="2" timestamp="2022-10-21T12:40:32 IST" time="0.152" errors="0">
  <testcase name="createProject" time="0.029" classname="com.actitime.testscript.ProjectModule">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.actitime.testscript.ProjectModule.createProject(ProjectModule.java:13)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- createProject -->
  <testcase name="createCustomer" time="0.005" classname="com.actitime.testscript.CustomerModule">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.actitime.testscript.CustomerModule.createCustomer(CustomerModule.java:13)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- createCustomer -->
</testsuite> <!-- Test(failed) -->
